### ISSUE TITLE
MDX pages have incomplete Title

### ISSUE THREAD

**Issue by gxjansen** [spryker-community/CommerceQuest-website#64] opened 2024-08-08 23:00 UTC
Pages like https://commercequest.space/coc/ show up in the browser as just `CommerceQuest`, but it should be `[page name] | CommerceQuest` (just as .astro pages).

**Comment by fsmeier** [comment] 2024-08-30 08:08
Is this a duplicate of #22 ?

**Comment by gxjansen** [comment] 2024-10-31 16:30
yes, duplicate

**Closed as not planned** 2024-10-31 16:31 UTC
Labels: enhancement
